### ISSUE TITLE
하위 메뉴가 있는 메뉴의 링크는 클릭할 수가 없음

### ISSUE THREAD

**Issue by khongchi** [xpressengine/plugin-alice#10]
![image](https://user-images.githubusercontent.com/1772843/28409363-5c966edc-6d75-11e7-9e1f-ba9716905c20.png)

```
게시판
  ㄴ 홈
```

메뉴 구조가 위와 같이 되어 있을 경우, 게시판 링크를 클릭할 수가 없습니다..

데스크탑의 경우, 아래와 같이 작동하는게 좋을것 같습니다.

- 마우스오버: 하위메뉴 펼침
- 클릭: 링크 이동

모바일의 경우, 메뉴 옆쪽에 별도의 펼침 버튼이 존재하면 좋을것 같습니다.

**Comment by seungmanchoi** [comment]
메뉴로 되어 있는 li부분이 padding-> margin으로 변경되어야함.
모바일일 경우 touch처리를 통해 메뉴 펼쳐짐이 가능하나 화살표 버튼이 작은 이슈가 있어 개선이 필요함
