### ISSUE TITLE
등록한 이미지를 삭제하는 옵션 추가를 건의합니다.

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/plugin-alice#8]
로고 이미지를 등록했을 때 이미지 없음으로 되돌리는 옵션이 필요할 것 같습니다.

![image](https://cloud.githubusercontent.com/assets/10809941/26678297/dc7074ae-470a-11e7-8d8c-c9db537288d5.png)

**Comment by khongchi** [comment]
https://github.com/xpressengine/xpressengine/issues/478
이슈에서 이미지 삭제 기능을 추가하였습니다 ^^
